server:
  port: 8768

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

hystrix:
  command:
      default:
        fallback:
          isolation:
            semaphore:
              maxConcurrentRequests: 3000
        execution:
          isolation:
            semaphore:
              maxConcurrentRequests: 3000
            strategy: SEMAPHORE
            thread:
              timeoutInMilliseconds: 400000

ribbon:
#  restclient:
#    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxTotalHttpConnections: 5000
  MaxHttpConnectionsPerHost: 5000
  ActiveConnectionsLimit: 4000
  eureka:
    enabled: true

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  semaphore:
    max-semaphores: 30000

spring:
  main:
    allow-bean-definition-overriding: true