server:
  port: 8768

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

hystrix:
  command:
      default:
        execution:
          isolation:
            strategy: THREAD
            thread:
                timeoutInMilliseconds: 41000

ribbon:
#  restclient:
#    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: true

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

spring:
  main:
    allow-bean-definition-overriding: true